
positive = ["You're doing a great job!",
"Keep up the excellent work!",
"Your efforts are truly appreciated.",
"You're on the right path!",
"I'm so proud of you!",
"Your hard work pays off.",
"You're making a big difference.",
"Stay positive, you're winning!",
"Believe in yourself, you can!",
"Your success is near!",
"Keep pushing, you're strong!",
"You're almost there, keep going!"]

neutral = ["The meeting is at 2 PM.",
"Please submit your report.",
"The deadline is next Friday.",
"We need to discuss this.",
"The project is ongoing.",
"We are reviewing the data.",
"The schedule is unchanged.",
"Please attend the seminar.",
"The policy remains the same.",
"We will update you soon.",
"The process is in progress.",
"We are analyzing the results."]

negative = ["You missed the deadline.",
"This is not acceptable.",
"Your performance is lacking.",
"We need to improve now.",
"This is a failure.",
"You're not meeting standards.",
"This is disappointing news.",
"We have to redo this.",
"Your work is subpar.",
"This is a setback.",
"We need better results.",
"This is not good enough."]